SELECT * FROM Omzet;

SELECT * FROM Product;

ALTER TABLE Omzet
ADD PRIMARY KEY (VerkoperNr, ProductNr);

ALTER TABLE Product
ADD PRIMARY KEY (ProductNr);

ALTER TABLE Omzet DROP CONSTRAINT VerkoperNr PRIMARY KEY;

ALTER TABLE Omzet
DROP CONSTRAINT PK__Omzet__7425C0490C292F34;

ALTER TABLE Omzet


SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_NAME='Omzet'

ALTER TABLE Omzet
ADD FOREIGN KEY (ProductNr) REFERENCES Product(ProductNr); 


ALTER TABLE Product
DROP PRIMARY KEY; 

ALTER TABLE Omzet
ADD CONSTRAINT FK_ProductNr_ProductNr FOREIGN KEY (ProductNr) REFERENCES Product(ProductNr)